app/models/usuario_model.py
from datetime import datetime

from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import login


class User(UserMixin, db.Model):
    __tablename__ = "usuario"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True)
    
    empresa = db.Column(db.String(20), index=True)
    telefone = db.Column(db.String(40), index=True)
    endereco = db.Column(db.String(50), index=True)
    pais = db.Column(db.String(10), index=True)
    estado = db.Column(db.String(10), index=True)
    cep = db.Column(db.String(10), index=True)

    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    files = db.relationship('FileContents', backref='user', lazy='dynamic')
    is_admin = db.Column(db.Boolean, default=False)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class FileContents(db.Model):
    __tablename__ = "files"

    id = db.Column(db.Integer, primary_key=True)
    descricao = db.Column(db.String(1000), index=True)
    servico = db.Column(db.String(50), index=True)
    file_name = db.Column(db.String(60))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    status = db.Column(db.String(15), default='Enviado')
    user_id = db.Column(db.Integer, db.ForeignKey('usuario.id'))


@login.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import SubmitField, StringField, TextAreaField, IntegerField, SelectField
from wtforms.validators import required, length


class UploadForm(FlaskForm):
    file = FileField('Image', validators=[required(), FileAllowed(['rar', 'zip'], 'Envie Arquivos no formato .zip e .rar')])
    descricao = TextAreaField('Descrição', validators=[required(), length(max=1000, message='Campo com mais de 1000 caracteres.')])
    servico = SelectField("Serviço", validators=[required()], choices=[("Dosimetria Clínica"), ("Dosimetria Pré-Clínica"), 
                                                                        ("Segmentação e Quantificação"), ("Modelagem Computacional"),
                                                                        ("Radiosinoviortese")])
    submit = SubmitField('Enviar')

app/__init__.py
import os

from flask import Flask
from flask_migrate import Migrate
from flask_login import LoginManager
from sqlalchemy.pool import QueuePool

from config import app_config
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy(engine_options={"pool_size": 10, "poolclass":QueuePool, "pool_pre_ping":True})
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
login.session_protection = 'strong'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(app_config[config_name])

    db.init_app(app)

    migrate.init_app(app, db)
    login.init_app(app)

    # diretorio para salvar os arquivos
    top_level_dir = os.path.abspath(os.curdir)
    upload_folder = top_level_dir
    app.config['UPLOAD_FOLDER'] = upload_folder

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp, url_prefix='/main')

    from app.admin import bp as admin_bp
    app.register_blueprint(admin_bp, url_prefix='/admin')

    return app


from .models import usuario_model

app/admin/__init__.py
from flask import Blueprint


bp = Blueprint('admin', __name__)

from app.admin import views

app/admin/views.py
from flask import abort, render_template, url_for, flash, jsonify
from werkzeug.utils import redirect

from app import db
from app.admin import bp
from flask_login import current_user, login_required

from app.auth.forms import RegistrationForm
from app.models import usuario_model
from app import s3_connection
import boto3
import botocore
import requests

def check_admin():
    if not current_user.is_admin:
        abort(403)


@bp.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():

    check_admin()

    lista = usuario_model.User.query.all()
    
    #form = RegistrationForm()
    #if form.validate_on_submit():
        #user = usuario_model.User(username=form.username.data, email=form.email.data)
        #user.set_password(form.password.data)
        #db.session.add(user)
        #db.session.commit()
        #flash('Parabéns, Cadastro com Sucesso!')
        #return redirect(url_for('admin.dashboard'))
    

    return render_template('admin/admin_dashboard.html', lista=lista)


@bp.route('/requisicoes', methods=['GET', 'POST'])
@login_required
def requisicoes():

    check_admin()

    lista_req = usuario_model.FileContents.query.all()

    return render_template('admin/admin_requisicoes.html', lista=lista_req)


@bp.route("/download/<int:id_arq>")
def download(id_arq):

    file = usuario_model.FileContents.query.filter_by(id=id_arq).first()
    arquivo_name = file.file_name

    url = s3_connection.download_s3(arquivo_name)

    if requests.get(url).status_code != 200:
        flash("Arquivo Indisponível para Download!", "warning")
        return redirect(url_for('admin.requisicoes'))

    return redirect(url)
        

@bp.route("/remover_cliente/<int:id>", methods=["GET", "POST"])
def remover_cliente(id):
    cliente = usuario_model.User.query.filter_by(id=id).first()

    try:
        db.session.delete(cliente)
        db.session.commit()
        flash("Usuário removido com Sucesso!", "success")
    except:
        flash("Erro! Usuário não foi removido!", "danger")

    return redirect(url_for("admin.dashboard"))



## Funcionalidades a serem implementadas
def editar_usuario():
    return "usuario editado"

def deletar_requisicao():
    return "requisicao deletada"

def editar_requisicao():
    return "requisicao editada"

app/main/__init__.py
from flask import Blueprint


bp = Blueprint('main', __name__)

from app.main import views, errors

app/main/views.py
from flask import render_template, request, url_for, flash, send_file
from flask_login import login_required, current_user
from werkzeug.utils import redirect, secure_filename
from app.main import bp
from app.main.forms import UploadForm
from app import usuario_model, db
from app import s3_connection


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    return render_template("index.html")


@bp.route("/upload", methods=['GET', 'POST'])
@login_required
def upload():
    form = UploadForm()
    if request.method == 'POST':

        if form.validate_on_submit():
            file = form.file.data
            if file != '':
                filename = secure_filename(file.filename)

                name = str(current_user.id) + '_' + '_' + filename

                #validar o nome do arquivo antes de enviar
                f_name = usuario_model.FileContents.query.filter_by(file_name=name).first()

                if f_name is None:
 
                    s3_connection.upload_s3(file, name)
                

                    new_file = usuario_model.FileContents(descricao=form.descricao.data, 
                                                        servico=form.servico.data,
                                                        file_name=name, 
                                                        user_id=current_user.id)
                    db.session.add(new_file)
                    db.session.commit()
                    flash("Arquivo Enviado com Sucesso!", "success")
                    return redirect(url_for('main.upload'))
                else:
                    flash("Já existe um arquivo com este nome. Renomei-o!", "danger")

                

    return render_template("upload.html", form=form)


@bp.route("/download/<int:id_arq>")
def download(id_arq):

    file = usuario_model.FileContents.query.filter_by(id=id_arq).first()
    arquivo_name = file.file_name

    url = s3_connection.download_s3(arquivo_name)

    return redirect(url) 


@bp.route("/lista", methods=["GET"])
def lista():

    # clientes = usuario_model.FileContents.query.all()
    cliente = usuario_model.FileContents.query.filter_by(user_id=current_user.id).all()
    return render_template("listar_arquivos.html", dados=cliente)


@bp.route("/principal", methods=["GET", "POST"])
def principal():

    return render_template("principal.html")

@bp.route("/upload_new", methods=["GET", "POST"])
def upload_new():

    return render_template("upload_new.html")

app/templates/error_layout.html
<!doctype html>
<html>

<head>
    <title> {% block title %} {% endblock %} </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/error.css') }}">

</head>

<body>

    <div class="wrapper d-flex align-items-stretch">

        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5 pt-5">

            {% block content %}
            {% endblock %}

        </div>


    </div>
    <!-- Scripts JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

</body>

</html>

app/templates/index.html
{% extends"layout.html" %}

{% block title %} Upload de Arquivos {% endblock %}

{% block content %}

<!-- Jumbotron Header -->

<div class="jumbotron jumbotron-fluid bg-gray">
    <div class="container-fluid">
        <h1>Seja Bem-Vindo, {{current_user.username}}!</h1>
        <p class="lead"> Estamos em construção... </p>
        <p class="lead"> Contamos com sua compreensão para eventuais problemas. Se possível, envie comentários para nos
            contar sobre sua experiência com a plataforma.</p>
        <p><a class="btn btn-primary btn-lg" href="{{url_for('main.upload')}}" role="button"> Solicitação de Serviços
                &raquo;</a></p>
    </div>
</div>

<div class="container-fluid text-center">
    <h1>Serviços</h1>
    <!--
    <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example.
        It's built with default Bootstrap components and utilities with little customization.</p>
    -->
</div>


<div class="container-fluid text-dark">


    <div class="card-deck">
        <div class="card" style="background-color: inherit; border: none;">
            <div class="card-header" style="background-color: inherit; border: none;">
                <h3> Dosimetria Clínica </h3>
            </div>
            <div class="card-body">

                <p class="card-text">Cálculo da dose absorvida (Gy) por unidade de atividade acumulada na região
                    fonte (MBq*h) baseado em
                    modelagem computacional, usando o processamento da imagem clínica do paciente obtida com
                    Tomografia
                    Computadoriza (CT), Ressonância Magnética Nuclear (RMN), Tomografia por Emissão de Fóton
                    Único (siglas
                    em inglês-SPECT) e Tomografia por Emissão de pósitron (siglas em inglês- PET)</p>

            </div>
        </div>
        <div class="card" style="background-color: inherit; border: none;">
            <div class="card-header" style="background-color: inherit; border: none;">
                <h3> Dosimetria pré-clínica </h3>
            </div>
            <div class="card-body">

                <p class="card-text">Dosimetria pré-clínica para o desenvolvimento de novos radiofármacos
                    baseado em modelagem
                    computacional
                    para o cálculo de dose absorvida (Gy) por unidade de atividade acumulada na região fonte
                    (MBq*h)
                    usando
                    o processamento da imagem tridimensional de modelos computacionais para pequenos animais</p>

            </div>
        </div>
        <div class="card" style="background-color: inherit; border: none;">
            <div class="card-header" style="background-color: inherit; border: none;">
                <h3> Segmentação e quantificação </h3>
            </div>
            <div class="card-body">

                <p class="card-text">Segmentação multirregional e quantificação de tumores, órgãos ou tecidos a
                    partir da imagem
                    tridimensional obtida com Tomografia Computadorizada (CT) ou Ressonância Magnética Nuclear
                    (RMN).</p>

            </div>
        </div>
        <div class="card" style="background-color: inherit; border: none;">
            <div class="card-header" style="background-color: inherit; border: none;">
                <h3> Modelagem Computacional </h3>
            </div>
            <div class="card-body">

                <p class="card-text">Modelagem Computacional para o estudo de sistemas de diagnóstico por imagem
                    médica como SPECT, PET e CT. Inclui-se também a modelagem computacional aplicada a problemas
                    de transporte do tipo fonte detector e experimentos complexos de radioterapia</p>

            </div>
        </div>
    </div>








</div>

</div> <!-- /container -->
{% endblock %}

app/templates/layout.html
<!doctype html>
<html>

<head>
  <title> {% block title %} {% endblock %} </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!--
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
-->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style_lay.css') }}">

  <style>
    body {
      font-family: 'Raleway', sans-serif;
      font-size: 14px;
      font-weight: 400;
      color: rgb(65, 64, 64);
    }

    h1 {
      font-size: 36px;
      color: #555;
      font-weight: bold;
    }

    h3 {
      font-size: 24px;
      color: #333;
      font-weight: bold;
    }

    /*
    #upload {
      opacity: 0;
    }

    #upload-label {
      position: absolute;
      top: 50%;
      left: 1rem;
      transform: translateY(-50%);
    }

    .image-area {
      border: 2px dashed rgba(255, 255, 255, 0.7);
      padding: 1rem;
      position: relative;
    }

    .image-area::before {
      content: 'Uploaded image result';
      color: #fff;
      font-weight: bold;
      text-transform: uppercase;
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      font-size: 0.8rem;
      z-index: 1;
    }

    .image-area img {
      z-index: 2;
      position: relative;
    }

    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .form-signin {
      width: 100%;
      margin: auto;
    }

    .form-label-group {
      position: relative;
      margin-bottom: 1rem;
    }

    .form-label-group>input,
    .form-label-group>label {
      height: 3.125rem;
      padding: .75rem;
    }

    .form-label-group>label {
      position: absolute;
      top: 0;
      left: 0;
      display: block;
      width: 100%;
      margin-bottom: 0;
      /* Override default `<label>` margin 
      line-height: 1.5;
      color: #495057;
      pointer-events: none;
      cursor: text;
      /* Match the input under the label 
      border: 1px solid transparent;
      border-radius: .25rem;
      transition: all .1s ease-in-out;
    }

    .form-label-group input::-webkit-input-placeholder {
      color: transparent;
    }

    .form-label-group input:-ms-input-placeholder {
      color: transparent;
    }

    .form-label-group input::-ms-input-placeholder {
      color: transparent;
    }

    .form-label-group input::-moz-placeholder {
      color: transparent;
    }

    .form-label-group input::placeholder {
      color: transparent;
    }

    .form-label-group input:not(:placeholder-shown) {
      padding-top: 1.25rem;
      padding-bottom: .25rem;
    }

    .form-label-group input:not(:placeholder-shown)~label {
      padding-top: .25rem;
      padding-bottom: .25rem;
      font-size: 12px;
      color: #777;
    }

    
    .jumbotron {
    background: none;
    } */

    .container-fluid {
      width: 90%;
    }
  </style>



</head>

<body>

  <div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar">
      <div class="custom-menu">
        <button type="button" id="sidebarCollapse" class="btn btn-primary">
        </button>
      </div>

      <div class="py-4 px-3 mb-4 bg-dark">
        <!--
              <div class="text-center">
                <h4 class="text-light"> Logo_Imagem </h4>
              </div>
               -->
        <div class="media d-flex align-items-center">
          <!--
          <img src="https://res.cloudinary.com/mhmd/image/upload/v1556074849/avatar-1_tcnd60.png" alt="..." width="65"
            class="mr-3 rounded-circle img-thumbnail shadow-sm">
            {{url_for('static', filename='images/Logo.png')}} 
          -->
          <img src="/static/images/Logo.png" alt="..." class="img-thumbnail">
          <!--
                    <div class="media-body">
                        <h4 class="m-0">Jason Doe</h4>
                        <p class="font-weight-light mb-0">Web developer</p>
                    </div>
                    -->
        </div>

      </div>
      <!--
      <div class="img bg-wrap text-center py-4" style="background-image: url(images/bg_1.jpg);">
        <div class="user-logo">
          <div class="img" style="background-image: url(images/logo.jpg);"></div>
          <h3>Catriona Henderson</h3>
        </div>
      </div>
      -->
      <ul class="list-unstyled components mb-5">
        <li class="active">
          <a href="{{ url_for('main.index') }}"><span class="fa fa-home mr-3"></span> Página Inicial</a>
        </li>
        <li class="active">
          <a href="{{ url_for('main.upload') }}"><span class="fa fa-upload mr-3"></span> Envio de Serviços</a>
        </li>
        <li class="active">
          <a href="{{ url_for('main.lista') }}"><span class="fa fa-file-archive-o mr-3"></span> Pedidos e Relatórios</a>
        </li>
        
        <!-- 
                <li>
                    <a href="#"><span class="fa fa-trophy mr-3"></span> Top Review</a>
                </li>
                -->
        <li>
          <a href="#"><span class="fa fa-cog mr-3"></span> Opções </a>
        </li>
        <li>
          <a href="#"><span class="fa fa-support mr-3"></span> Suporte </a>
        </li>
        <li class="active">
          <a href="{{ url_for('auth.logout') }}"><span class="fa fa-sign-out mr-3"></span> Sair </a>
        </li>
      </ul>

    </nav>

    <!-- Page Content class="p-4 p-md-5 pt-5" -->
    <div id="content" class="pt-0">

      {% block content %}


      {% endblock %}

    </div>


  </div>
  <!-- Scripts JS 
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>-->


  <!--
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
-->

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js" crossorigin="anonymous"></script>
  <!--
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" crossorigin="anonymous"></script>
  -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"
    crossorigin="anonymous"></script>




  <script src="{{ url_for('static', filename='js/main.js') }}"></script>

  <script src="{{ url_for('static', filename='js/multistep.js') }}"></script>

</body>

</html>

app/templates/lista.html
{% extends"layout.html" %}

{% block title %} Pagina Inicial {% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h3> Dados do Cliente</h3>
    </div>
    <div class="body">
        <div class="container">
            <h5 class="card-title">Arq: {{ dados.file_name}}</h5>


        </div>


    </div>
</div>
{% endblock %}

app/templates/listar_arquivos.html
{% extends"layout.html" %}

{% block title %} Requisições {% endblock %}

{% block content %}
<div class="container-fluid py-5 text-left">

    <div>
        <h3>Acompanhamento de Requisições:</h3>
        <p>Siga o andamento de suas requisições através da coluna <b>status</b>. Quando seu pedido
            receber o <b>status:</b> <b> Concluído</b>,  será disponibilizado um link para ser feito o download. </p>
        <p>Tipos de Status: <b>Enviado, Recebido, Validando, Simulando, Concluído.</b> </p>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Serviço</th>
                <th>Descrição do Projeto</th>
                <th>Data/Hora de Envio</th>
                <th>Status</th>
                <th> Download </th>
            </tr>
        </thead>
        <tbody>
            {% for i in dados %}
            <tr>
                <td>{{i.servico}}</td>
                <td>{{i.descricao}}</td>
                <td>{{i.timestamp}}</td>
                <td> {{i.status}} </td>
                <!-- {{ url_for('main.download', id_arq=i.id) }} -->
                <td> <a href="#"><span class="fa fa-download"></span></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/registrar.html
{% extends"layout.html" %}

{% block title %} Upload de Arquivos {% endblock %}

{% block content %}

<div class="col-md-8 order-md-1">
    
    <form class="needs-validation">
      <!-- Nome -->
        <div class="mb-3">
          <label for="name">Nome (Responsável Técnico)</label>
          <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text"> <i class="fa fa-user"></i> </span>
              </div>
            <input type="text" class="form-control" id="name" placeholder="" value="" required>
          </div>
        </div>
    
        <!-- Empresa  -->
      <div class="mb-3">
        <label for="empresa">Empresa</label>
        <div class="input-group">

          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-address-card"></i> </span>
          </div>

          <input type="text" class="form-control" id="empresa" placeholder="Empresa" required>
        </div>
      </div>

      <!-- Email  -->
      <div class="mb-3">
        <label for="email">Email</label>
        <div class="input-group">

          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
          </div>

          <input type="text" class="form-control" id="email" placeholder="Email" required>
        </div>
      </div>

      <!-- Password  -->
      <div class="mb-3">
        <label for="senha">Senha</label>
        <div class="input-group">

          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>

          <input type="text" class="form-control" id="senha" placeholder="******" type="password"required>
        </div>
      </div>

      <!-- Password 2  -->
      <div class="mb-3">
        <label for="senha2">Senha (Digite Novamente)</label>
        <div class="input-group">

          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>

          <input type="text" class="form-control" id="senha2" placeholder="******" type="password" required>
        </div>
      </div>

      <!-- Endereco -->
      <div class="mb-3">
        <label for="endereco">Endereço</label>
        <div class="input-group">

          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-map-marker"></i> </span>
          </div>

          <input type="text" class="form-control" id="endereco" placeholder="Endereço" required>
        </div>
      </div>
      <!-- Estado / País / CEP -->
      <div class="row">
        <div class="col-md-5 mb-3">
          <label for="country">País</label>
          <input type="text" class="form-control" id="country" placeholder="" required>
        </div>
        <div class="col-md-4 mb-3">
          <label for="state">Estado</label>
          <input type="text" class="form-control" id="state" placeholder="" required>
        </div>
        <div class="col-md-3 mb-3">
          <label for="zip">CEP</label>
          <input type="text" class="form-control" id="zip" placeholder="" required>
        </div>
      </div>

      
      
      <hr class="mb-4">

      <h4 class="mb-3">Administrador: </h4>

      <div class="d-block my-3">
        <div class="custom-control custom-radio">
          <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" required>
          <label class="custom-control-label" for="credit">Sim</label>
        </div>
        <div class="custom-control custom-radio">
          <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
          <label class="custom-control-label" for="debit">Não</label>
        </div>
      </div>
      <!--
      <h4 class="mb-3">Serviço: </h4>

      <div class="d-block my-3">
        <div class="custom-control custom-radio">
          <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
          <label class="custom-control-label" for="credit">Credit card</label>
        </div>
        <div class="custom-control custom-radio">
          <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
          <label class="custom-control-label" for="debit">Debit card</label>
        </div>
        <div class="custom-control custom-radio">
          <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
          <label class="custom-control-label" for="paypal">Paypal</label>
        </div>
      </div>
      -->

      

      <hr class="mb-4">
      <button class="btn btn-primary btn-lg btn-block" type="submit">Cadastrar</button>
    </form>
  </div>

{% endblock %}